account_app/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
    path('register', register_view, name='register'),
    path('logout', logout_view, name='logout'),
]

chatbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls', namespace='account')),
    path('chat/', include('chatbot_app.urls', namespace="chat")),
]

chatbot_app/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.chat_page, name='script')
]

account_app/models.py
from django.db import models
import uuid


class UserAccount(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return str(self.username)


class SessionToken(models.Model):
    username = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    token = models.CharField(max_length=250)
    created_on = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField(default=True)

    def create_token(self):
        self.token = uuid.uuid4()

    def __str__(self):
        return str(self.username)

chatbot_app/models.py
from django.db import models
from account_app.models import UserAccount


class Chat(models.Model):
    # name = models.ForeignKey(UserAccount, default='', null=True, on_delete=models.CASCADE)
    # username = models.CharField(max_length=100, default='')
    message = models.CharField(max_length=100, default='')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.message)

account_app/forms.py
from django import forms
from .models import *


class RegisterUser(forms.ModelForm):
    class Meta:
        model = UserAccount
        fields = ['name', 'email', 'username', 'password']


class LoginUser(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

chatbot_app/forms.py
from django import forms
from .models import Chat


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = [
            'message',
        ]

account_app/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .forms import *
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages


def home_view(request):
    home = True
    return render(request, 'home.html', {'home': home})


def register_view(request):
    reg = True
    if request.method == 'POST':
        register_form = RegisterUser(request.POST)
        if register_form.is_valid():
            name = register_form.cleaned_data['name']
            username = register_form.cleaned_data['username']
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password']
            obj = UserAccount(name=name, username=username, email=email, password=make_password(password))
            obj.save()
            return redirect('account:login')
    else:
        register_form = RegisterUser()
    return render(request, 'account_app/register.html', {'form': register_form, 'register': reg, 'errors': register_form.errors})


def login_view(request):
    log = True
    if request.method == 'POST':
        login_form = LoginUser(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            obj = UserAccount.objects.filter(username=username).first()
            if obj is None:
                return render(request, 'account_app/login.html', {'error': "Username does not exist"})
            else:
                if check_password(password, obj.password):
                    token = SessionToken(username=obj)
                    token.create_token()
                    token.save()
                    response = redirect('chat:script')
                    response.set_cookie(key='SessionToken', value=token.token)
                    return response
                else:
                    messages.error(request, "Wrong Password")
        else:
            messages.error(request, "Invalid input")
            return render(request, 'account_app/login.html')
    else:
        login_form = LoginUser()
    return render(request, 'account_app/login.html', {'form': login_form, 'login': log})


def check_validation(request):
    if request.COOKIES.get('SessionToken'):
        session = SessionToken.objects.filter(token=request.COOKIES.get('SessionToken')).first()
        if session:
            return session.username
    else:
        return None


def logout_view(request):
    user = check_validation(request)
    if user:
        token = SessionToken.objects.filter(username=user)
        token.delete()
        return redirect('account:home')
    else:
        return redirect('account:login')

chatbot_app/views.py
from django.shortcuts import render, redirect
from .forms import ChatForm
from .chatbot import chat
from account_app.views import check_validation
from account_app.models import UserAccount


def chat_page(request):
    gif = True
    user = check_validation(request)
    if user:
        if request.method == 'POST':
            form = ChatForm(request.POST)
            if form.is_valid():
                form.save()
            inp = request.POST.get('message')
            reply = chat(inp)
            bot = 'Bot:'
            context = {
                'botreply': reply,
                'userreply': inp,
                'bot': bot,
                'gif': gif,
                'msg_send': user,
            }
            return render(request, 'chatbot_app/chat.html', context)
        else:
            return render(request, 'chatbot_app/chat.html', {'gif': gif, 'user': user})

    else:
        return redirect('account:login')

account_app/templates/account_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/apple-icon.png' %}">
    <!-- CSS Files -->
    <link href="{% static 'css/argon-design-system.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <title>{% block title %}Home{% endblock %}</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">
    <!-- Nucleo Icons -->
    <link rel="stylesheet" href="{% static 'css/nucleo-icons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nucleo-svg.css' %}"/>
    <!-- Font Awesome Icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
</head>
<body class="login-page">
    {% block banner %}
    {% endblock %}

    {% block navbar %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/datetimepicker.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
<!-- Control Center for Argon UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->
<!--<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
<script src="{% static 'js/argon-design-system.min.js' %}" type="text/javascript"></script>
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
<script>
window.TrackJS &&
  TrackJS.install({
    token: "ee6fab19c5a04ac1a32a645abde4613a",
    application: "argon-design-system-pro"
  });
</script>
</body>
</html>

account_app/templates/account_app/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block content %}
<section class="section section-shaped section-lg">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0" style="margin-top: -90px;">
                    <div class="card-header bg-light pb-3">
                        <div class="text-dark text-center mb-3"><b>Sign in</b></div>
                        <div class="btn-wrapper text-center">
                            <div class="rounded mx-auto d-block">
                                <img src="{% static 'images/brand/bot.gif' %}" style="width: 100px;">
                            </div>
                        </div>
                    </div>
                    <div class="card-body bg-primary px-lg-5 py-lg-5">
                        <form role="form" method="POST">
                            {% csrf_token %}
                            <div class="text-danger">
                                {% if messages %}
                                {% for msg in messages %}
                                {{ msg }}
                                {% endfor %}
                                {% endif %}
                                {{ error }}
                            </div>
                            <div class="form-group mb-3">
                                <div class="input-group input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Username"  name="username" id="username" required>
                                </div>
                            </div>
                            <div class="form-group focused">
                                <div class="input-group input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                    </div>
                                    <input type="password" class="form-control" placeholder="Password" name="password" id="password" required>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-white my-4">Sign in</button>
                            </div>
                        </form>
                                <a href="{% url 'account:register' %}" class="text-white"><small>Create account</small></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

account_app/templates/account_app/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block banner %}
    <div class="banner"> </div>
{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block content %}
<div class="wrapper">
  <section class="section section-shaped section-lg">
      <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div class="container pt-lg-7">
          <div class="row justify-content-center">
              <div class="col-lg-5">
                  <div class="card bg-secondary shadow border-0" style="margin-top: -90px;" >
                      <div class="card-header bg-light pb-3">
                          <div class="text-dark text-center mb-3"><b>Register</b></div>
                          <div class="btn-wrapper text-center">
                              <div class="rounded mx-auto d-block">
                                  <img src="{% static 'images/brand/bot.gif' %}" style="width: 100px;">
                              </div>
                          </div>
                      </div>
                      <div class="card-body bg-primary px-lg-5 py-lg-5">
                          <form role="form" method="POST">
                              {% csrf_token %}
                              <div class="text-danger">
                                  {% if errors %}
                                    {% for error in errors %}
                                        {{ error }} already exists.<br>
                                    {% endfor %}
                                  {% endif %}
                              </div>
                              <div class="form-group">
                                  <div class="input-group input-group-alternative mb-3">
                                      <div class="input-group-prepend">
                                          <span class="input-group-text"><i class="fas fa-user"></i></span>
                                      </div>
                                    <input class="form-control" placeholder="Name" type="text" name="name" id="name" required>
                                  </div>
                              </div>
                              <div class="form-group">
                                  <div class="input-group input-group-alternative mb-3">
                                      <div class="input-group-prepend">
                                          <span class="input-group-text"><i class="fas fa-user"></i></span>
                                      </div>
                                    <input class="form-control" placeholder="Username" type="text" name="username" id="username" required>
                                  </div>
                              </div>
                              <div class="form-group">
                                  <div class="input-group input-group-alternative mb-3">
                                      <div class="input-group-prepend">
                                          <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                                      </div>
                                    <input class="form-control" placeholder="Email" type="email" name="email" id="email" required>
                                  </div>
                              </div>
                              <div class="form-group focused">
                                  <div class="input-group input-group-alternative">
                                      <div class="input-group-prepend">
                                          <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                      </div>
                                    <input class="form-control" placeholder="Password" type="password" name="password" id="pass" required>
                                  </div>
                              </div>
                              <div class="text-center">
                                  <button type="submit" class="btn btn-white mt-4" name="signup" id="signup">Create account</button>
                              </div>
                          </form>
                      </div>
                  </div>
            </div>
          </div>
      </div>
  </section>
</div>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

chatbot_app/templates/chatbot_app/chat.html
{% extends "base.html" %}
{% load static %}

{% block title %} Chat {% endblock %}
{% block banner %}
    <div class="banner"></div>
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
<section class="section section-shaped section-lg">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0" style="margin-top: -90px;">
                    {% if msg_send %}
                    <div class="card-header bg-dark pb-5 pt-3">
                        <div class="text-muted text-center mb-4">
                            <i class="far fa-comments"></i>&nbsp;<b>Chat Box</b>
                        </div>
                        <div class="alert alert-light alert-light text-dark text-left">
                            <b>{{ bot }}</b> {{ botreply }}
                        </div>
                        <div class="alert alert-light text-dark text-left">
                            <b>{{ msg_send }}:</b> {{ userreply }}
                        </div>
                    </div>
                    {% else %}
                    <div class="card-header bg-dark pb-5 pt-3">
                        <div class="text-muted text-center mb-4">
                            <i class="far fa-comments"></i>&nbsp;<b>Chat Box</b>
                        </div>
                        <div class="alert alert-light alert-light text-dark text-left">
                            <b>Bot: </b> Welcome {{ user }}
                        </div>
                        <div class="alert alert-light text-dark text-left">
                            <b>{{ user }}:</b> <small>Type message to get reply</small>
                        </div>
                    </div>
                    {% endif %}
                    <div class="card-body bg-primary pt-5">
                        <form action="{% url 'chat:script' %}" role="form" method="POST">
                            {% csrf_token %}
                            <div class="form-group focused">
                                <div class="input-group input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Type your message" name="message" id="password" required>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-white my-4">Send</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/favicon1.png' %}">
    <!-- CSS Files -->
    <link href="{% static 'css/argon-design-system.css' %}" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <!-- Nucleo Icons -->
    <link rel="stylesheet" href="{% static 'css/nucleo-icons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nucleo-svg.css' %}"/>
    <!-- Font Awesome Icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
</head>
<body class="login-page">
    {% block banner %}
    {% endblock %}

    {% block navbar %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/datetimepicker.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
<!-- Control Center for Argon UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->
<!--<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
<script src="{% static 'js/argon-design-system.min.js' %}" type="text/javascript"></script>
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
<script>
window.TrackJS &&
  TrackJS.install({
    token: "ee6fab19c5a04ac1a32a645abde4613a",
    application: "argon-design-system-pro"
  });
</script>
</body>
</html>

templates/footer.html
{% load static %}
{% block footer %}
<footer class="footer">
    <div class="container">
        <div class="row row-grid align-items-center mb-5">
            <div class="col-lg-6 text-lg-center btn-wrapper">
                <button target="_blank" href="https://twitter.com/" rel="nofollow" class="btn btn-icon-only btn-twitter rounded-circle" data-toggle="tooltip" data-original-title="Follow us">
                    <span class="btn-inner--icon"><i class="fa fa-twitter"></i></span>
                </button>
                <button target="_blank" href="https://www.facebook.com/" rel="nofollow" class="btn-icon-only rounded-circle btn btn-facebook" data-toggle="tooltip" data-original-title="Like us">
                    <span class="btn-inner--icon"><i class="fab fa-facebook"></i></span>
                </button>
                <button target="_blank" href="https://github.com/" rel="nofollow" class="btn btn-icon-only btn-github rounded-circle" data-toggle="tooltip" data-original-title="Star on Github">
                    <span class="btn-inner--icon"><i class="fa fa-github"></i></span>
                </button>
            </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-md-between">
            <div class="col-md-6">
                <div class="copyright">
                    &copy; 2020 <a href="#">Chatbot</a>.
                </div>
            </div>
            <div class="col-md-6">
                <ul class="nav nav-footer justify-content-end">
                    <li class="nav-item">
                        <a href="#" class="nav-link">Chatbot</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:register' %}" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Contact us</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

templates/navbar.html
{% load static %}
{% block navbar %}
<nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
    <div class="container">
        <a class="navbar-brand mr-lg-5"  href="{% url 'account:home' %}">
            {% if gif %}
                <img src="{% static 'images/brand/bot.gif' %}" style="height: 100px;">
            {% else %}
                <img src="{% static 'images/brand/logo.png' %}" style="height: 80px;">
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav align-items-lg-center ml-lg-auto">
            <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://www.facebook.com/" target="_blank" data-toggle="tooltip" title="Like us on Facebook">
                    <i class="fa fa-facebook-square"></i>
                    <span class="nav-link-inner--text d-lg-none">Facebook</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://www.instagram.com/" target="_blank" data-toggle="tooltip" title="Follow us on Instagram">
                    <i class="fa fa-instagram"></i>
                    <span class="nav-link-inner--text d-lg-none">Instagram</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://twitter.com/" target="_blank" data-toggle="tooltip" title="Follow us on Twitter">
                    <i class="fa fa-twitter-square"></i>
                    <span class="nav-link-inner--text d-lg-none">Twitter</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://github.com/" target="_blank" data-toggle="tooltip" title="Star us on Github">
                    <i class="fa fa-github"></i>
                    <span class="nav-link-inner--text d-lg-none">Github</span>
                </a>
            </li>
            <li class="nav-item d-none d-lg-block ml-lg-4">
                {% if register %}
                <a href="{% url 'account:login' %}" class="btn btn-neutral btn-icon text-dark">
                    <span class="btn-inner--icon"><i class="fas fa-sign-in-alt mr-2"></i></span>
                    <span class="nav-link-inner--text">Login</span>
                </a>
                {% elif error %}
                 <a href="{% url 'account:register' %}" class="btn btn-neutral btn-icon text-dark">
                     <span class="btn-inner--icon"><i class="fas fa-sign-in-alt mr-2"></i></span>
                     <span class="nav-link-inner--text">Register</span>
                 </a>
                {% elif login %}
                <a href="{% url 'account:register' %}" class="btn btn-neutral btn-icon text-dark">
                    <span class="btn-inner--icon"><i class="fas fa-sign-out-alt mr-2"></i></span>
                    <span class="nav-link-inner--text">Register</span>
                </a>
                {% elif home %}
                <a href="{% url 'account:register' %}" class="btn btn-neutral btn-icon text-dark">
                    <span class="btn-inner--icon"><i class="fas fa-sign-out-alt mr-2"></i></span>
                    <span class="nav-link-inner--text">Register</span>
                </a>
                {% else %}
                <a href="{% url 'account:logout' %}" class="btn btn-neutral btn-icon text-dark">
                    <span class="btn-inner--icon"><i class="fas fa-sign-out-alt mr-2"></i></span>
                    <span class="nav-link-inner--text">Logout</span>
                </a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!-- End Navbar -->
{% endblock %}